### PR TITLE
Feature/apitest

### LINKED ISSUE #7: test apis

### PR DESCRIPTION
**Pull request by jathek**
lots of lines changed but I think it's because I formatted with prettier before submitting and Gene hadn't. I only added the youtube fetch and then tweaked the classes to be ids in the queryselectors.

closes  #7

### CODE REVIEW

**Comment by IIMacGyverII** [comment]
cool

**Comment by nearcatch** [comment]
closes https://github.com/ggrove87/nu-project-1/issues/7

**Comment by jathek** [comment]
did you mean to close this without merging @IIMacGyverII, or do I need to change something?

**Comment by IIMacGyverII** [comment]
No. I’m sorry. I was trying to merge it but I don’t believe I have permissions because you requested only gene to review?


Sent from Yahoo Mail for iPhone


On Monday, April 11, 2022, 4:00 PM, jason ***@***.***> wrote:




did you mean to close this without merging Joshua, or do I need to change something?

**Comment by jathek** [comment]
Sorry I wasn't sure what that would do. I'll unrequest him.

**Review by ggrove87 — APPROVED** [review]
Changes look good, will the storeMovieData function work without the input from the pullMovieInfo function?

**Comment by jathek** [comment]
> Changes look good, will the storeMovieData function work without the input from the pullMovieInfo function?

I commented that out to debug something and forget to flip it back. I'll do it tomorrow in a new pr.

**Pull request merged**
